---
- name: fixed
  desciption:
    Paralax effect where background stays fixed
    during scrolling
  values: on off
  default: off
- name: columns
  desciption:
    Number of columns in a layout that supports cards
  values: 2 3 4
  default: 3
- name: background
  desciption:
    Background colors. Light colors stay with black text.
    Solid colors invert to white text.
  values: white none light_blue light_gray light_orange solid_blue solid_red solid_indigo
  default: none
- name: color
  desciption:
    Text colors. Don't use with solid background colors.
    Same colors as background available. Default none, meas as parent.
  values: none white black light_blue light_gray solid_black solid_blue solid_red solid_indigo
  default: none
- name: shade_color
  desciption:
    Color of transparent shaded area.
    The number means transparency.
  values: none black_25 white_25 light_red_25 light_blue_25 solid_blue_25 solid_red_25
  default: none
- name: align
  desciption:
    Align text of children. Normal Word meaning
  values: left center right
  default: left
- name: order
  desciption:
    For two column layout determine order of sub-cards
    Values of left and right usually refer to where the image is
    For cards it can also mean up and down
  values: left right
  default: left
- name: margin
  desciption:
    Most sections have standard margin of 20.
    This option makes it possible to remove that
  values: 0 20
  default: 20
- name: button_text
  desciption:
    Text for an optional button. Must also set button_link
  values:
  default:
- name: subheader
  desciption:
    Smaller header between Header and text
  values:
  default:
- name: text
  desciption:
    Second text. Just a second paragraph
  values:
  default:
- name: button_link
  desciption:
    Link for an option button. Must also set button_text.
    Link must be a page name, ie only internal links allowed.
  values:
  default:
