---
- type: page
  description: A general page, may contain anykind of section.
        No restrictions of any kind. No options either.
  options:
    - meta
- type: blog
  description: An news or similar article.
  section_template: blog_header
  options:
    - published_date
    - date_precision
