---
- template: section_cards
  header: Section with Cards, 2-6 columns
  text: A header with text and column layout. Columns have a little gap, so
    background color comes through. 2 - 6 columns. Cards freely choosable
  cards: true
  fields:
    - header
    - text
  options:
    - background
    - columns
    - subheader
    - color
    - text_align
- template: section_feature
  header: Feature section with 2 column,
  text: A split header with two column layout on the right.
        Cards can be choosen freely but columns should be carefully
        choosen to fit.
  cards: true
  fields:
    - header
    - text
  options:
    - background
    - columns
    - subheader
    - color
    - text_align
- template: section_full_up
  header: Centered Header with text
  text: Full width header with centered headline and optional text
  fields:
    - header
    - text
  options:
    - background
    - color
    - margin
    - subheader
    - text_align
    - item_align
    - button_link
    - button_text
- template: section_news
  header: Showing latest news
  text: Always the latest available news section
  fields:
    - header
    - text
  options:
    - background
    - color
    - text_align
    - item_align
    - button_link
    - button_text
- template: section_text
  header: Newspaper style section for longer passages of text.
  text: Text may be markdown. The section may have one image than
        can be embedded into the text by writing IMAGE (in caps)
        where the image should be inserted. Not more than 200 words
        or 1000 characters are best.
  fields:
    - header
    - text
  options:
    - columns
    - background
    - color
    - margin
    - subheader
- template: section_half_image
  header: Split section with image left or right
  text: Image on one side, header and text on the other.
    Order depends on order option. Optional button.
  fields:
    - header
    - text
  options:
    - order
    - background
    - color
    - subheader
    - text_align
    - button_link
    - button_text
- template: section_full_image
  header: Full image header with adjustable text
  text: Large picture background with Header and text on top.
    Adjustable text text alignment (left, center, right).
    Text may be slightly shaded for readability,
    text color can be changed too.
  fields:
    - header
    - text
  options:
    - fixed
    - color
    - text_align
    - item_align
    - image_align
    - shade_color
- template: section_large_image
  header: Two third image header with adjustable text
  text: Large picture background with Header and text offset.
    Adjustable text alignment (left, center, right).
    Text section may have background color.
    Text color can be changed too
  fields:
    - header
    - text
  options:
    - subheader
    - margin
    - order
    - color
    - background
- template: section_spacer
  header: Spacer
  text: Just for extra padding
  fields:
- template: form_section
  header: Contact or other form
  text: Flexible form, with input fields as "cards". Only choose form_field
        as contained in the form.
  cards: true
  fields:
    - header
    - text
  options:
    - ok_message
    - handler
    - background
    - color
- template: blog_header
  header: Start of blog, with image left or right
  text: Image on one side, header and text on the other.
    Order depends on order option. Date is subheader.
    Extra text possible under both text and picture, as markdown.
  fields:
    - header
    - text
  options:
    - order
    - columns
    - background
    - color
